package com.taskmanager.model.entity;

import com.taskmanager.model.enums.Role;
import jakarta.persistence.*;
import lombok.*;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 * User entity represents a registered user in our task management system.
 * 
 * This class implements Spring Security's UserDetails interface, which means
 * Spring Security can use it directly for authentication and authorization.
 * The UserDetails interface requires us to implement methods like getUsername(),
 * getPassword(), getAuthorities(), etc.
 * 
 * We use Lombok annotations (@Data, @Builder, etc.) to automatically generate
 * boilerplate code like getters, setters, constructors, and builder pattern.
 * This keeps our entity class clean and focused on the actual fields.
 * 
 * The @Entity annotation tells JPA (Hibernate) that this class maps to a
 * database table. The @Table annotation lets us customize the table name -
 * we use "users" because "user" is a reserved keyword in some databases.
 */
@Entity
@Table(name = "users")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User implements UserDetails {

    /**
     * Primary key - auto-generated by the database.
     * We use IDENTITY strategy which lets the database handle ID generation.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * User's display name (e.g., "John Doe").
     * Cannot be null because every user needs a name to display.
     */
    @Column(nullable = false)
    private String name;

    /**
     * User's email address - used as the username for login.
     * Must be unique because we look up users by email during authentication.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * Hashed password - we NEVER store plain text passwords.
     * The password is hashed using BCrypt before being stored.
     * BCrypt is a one-way hash, so even if the database is compromised,
     * the actual passwords cannot be recovered.
     */
    @Column(nullable = false)
    private String password;

    /**
     * User's role determines what they can do in the system.
     * @Enumerated(STRING) stores the enum name as text in the database
     * (e.g., "USER" or "ADMIN") instead of ordinal numbers, which is
     * safer because the order of enum values might change.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private Role role = Role.USER;

    /**
     * Refresh token for JWT token renewal.
     * When the access token expires, the client can use this refresh token
     * to get a new access token without requiring the user to log in again.
     */
    @Column(name = "refresh_token")
    private String refreshToken;

    /**
     * Timestamp of when this user account was created.
     * @PrePersist sets this automatically when the entity is first saved.
     */
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp of the last update to this user record.
     * @PreUpdate sets this automatically whenever the entity is updated.
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * One-to-many relationship with tasks.
     * A user can have many tasks assigned to them.
     * cascade = ALL means operations on the user cascade to their tasks.
     * orphanRemoval = true means if a task is removed from this list,
     * it gets deleted from the database too.
     */
    @OneToMany(mappedBy = "assignee", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<Task> tasks = new ArrayList<>();

    // ---------- JPA Lifecycle Callbacks ----------

    /**
     * Called automatically by JPA before the entity is first persisted (saved).
     * We use this to set the creation timestamp.
     */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * Called automatically by JPA before the entity is updated.
     * We use this to update the "last modified" timestamp.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    // ---------- UserDetails Interface Methods ----------
    // These methods are required by Spring Security's UserDetails interface.

    /**
     * Returns the authorities (permissions) granted to the user.
     * We convert our Role enum to a GrantedAuthority with "ROLE_" prefix,
     * which is the standard convention in Spring Security.
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return List.of(new SimpleGrantedAuthority("ROLE_" + role.name()));
    }

    /**
     * Spring Security uses this to get the username for authentication.
     * In our case, the email serves as the username.
     */
    @Override
    public String getUsername() {
        return email;
    }

    /**
     * These methods control account status. For simplicity in this project,
     * we always return true (all accounts are active and non-expired).
     * In a production app, you might add fields to control these.
     */
    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return true;
    }
}
